export type Stock = {
    particulars: string //(Stock Name)
    purchasePrice: number
    quantity: number
    investment: number //(Purchase Price × Qty)
    portfolio: number //(%) (Proportional weight in the portfolio)
    nse_bse: string //(Stock Exchange Code)
    cmp: number | string //(Fetched from Yahoo Finance)
    presentValue: number | string//(CMP × Qty)
    gain_loss: number //(Present Value – Investment)
    peRatio: number //(Fetched from Google Finance)
    latestEarnings: number //(Fetched from Google Finance)
    dataReady?: boolean
};

export type Portfolio = Stock[];

export const initialPortfolio: Portfolio = [
    {
        particulars: 'Bajaj Finance',
        purchasePrice: 6466,
        quantity: 15,
        nse_bse: 'BAJFINANCE',
        investment: 96990,
        portfolio: 6,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'ICICI Bank',
        purchasePrice: 780,
        quantity: 84,
        nse_bse: '532174',
        investment: 65520,
        portfolio: 4,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Bajaj Housing',
        purchasePrice: 130,
        quantity: 504,
        nse_bse: '544252',
        investment: 65520,
        portfolio: 4,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Savani Financials',
        purchasePrice: 24,
        quantity: 1080,
        nse_bse: '511577',
        investment: 25920,
        portfolio: 2,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Affle India',
        purchasePrice: 1151,
        quantity: 50,
        nse_bse: 'AFFLE',
        investment: 57550,
        portfolio: 4,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'LTI Mindtree',
        purchasePrice: 4775,
        quantity: 16,
        nse_bse: 'LTIM',
        investment: 76400,
        portfolio: 5,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'KPIT Tech',
        purchasePrice: 672,
        quantity: 61,
        nse_bse: '542651',
        investment: 40992,
        portfolio: 3,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Tata Tech',
        purchasePrice: 1072,
        quantity: 63,
        nse_bse: '544028',
        investment: 67536,
        portfolio: 4,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'BLS E-Services',
        purchasePrice: 232,
        quantity: 191,
        nse_bse: '544107',
        investment: 44312,
        portfolio: 3,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Tanla',
        purchasePrice: 1134,
        quantity: 45,
        nse_bse: '532790',
        investment: 51030,
        portfolio: 3,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Dmart',
        purchasePrice: 3777,
        quantity: 27,
        nse_bse: 'DMART',
        investment: 101979,
        portfolio: 7,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Tata Consumer',
        purchasePrice: 845,
        quantity: 90,
        nse_bse: '532540',
        investment: 76050,
        portfolio: 5,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Pidilite',
        purchasePrice: 2376,
        quantity: 36,
        nse_bse: '500331',
        investment: 85536,
        portfolio: 6,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Tata Power',
        purchasePrice: 224,
        quantity: 225,
        nse_bse: '500400',
        investment: 50400,
        portfolio: 3,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'KPI Green',
        purchasePrice: 875,
        quantity: 50,
        nse_bse: '542323',
        investment: 43750,
        portfolio: 3,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Suzlon',
        purchasePrice: 44,
        quantity: 450,
        nse_bse: '532667',
        investment: 19800,
        portfolio: 1,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Gensol',
        purchasePrice: 998,
        quantity: 45,
        nse_bse: '542851',
        investment: 44910,
        portfolio: 3,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Hariom Pipes',
        purchasePrice: 580,
        quantity: 60,
        nse_bse: '543517',
        investment: 34800,
        portfolio: 2,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Astral',
        purchasePrice: 1517,
        quantity: 56,
        nse_bse: 'ASTRAL',
        investment: 84952,
        portfolio: 6,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Polycab',
        purchasePrice: 2818,
        quantity: 28,
        nse_bse: '542652',
        investment: 78904,
        portfolio: 5,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Clean Science',
        purchasePrice: 1610,
        quantity: 32,
        nse_bse: '543318',
        investment: 51520,
        portfolio: 3,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Deepak Nitrite',
        purchasePrice: 2248,
        quantity: 27,
        nse_bse: '506401',
        investment: 60696,
        portfolio: 4,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Fine Organic',
        purchasePrice: 4284,
        quantity: 16,
        nse_bse: '541557',
        investment: 68544,
        portfolio: 4,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Gravita',
        purchasePrice: 2037,
        quantity: 8,
        nse_bse: '533282',
        investment: 16296,
        portfolio: 1,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'SBI Life',
        purchasePrice: 1197,
        quantity: 49,
        nse_bse: '540719',
        investment: 58653,
        portfolio: 4,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Infy',
        purchasePrice: 1647,
        quantity: 36,
        nse_bse: '500209',
        investment: 59292,
        portfolio: 4,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'Happiest Minds',
        purchasePrice: 1103,
        quantity: 45,
        nse_bse: '543237',
        investment: 49635,
        portfolio: 3,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    },
    {
        particulars: 'EaseMyTrip',
        purchasePrice: 20,
        quantity: 1332,
        nse_bse: '543272',
        investment: 26640,
        portfolio: 2,
        cmp: 0,
        presentValue: 0,
        gain_loss: 0,
        peRatio: 0,
        latestEarnings: 0,
    }
];

export const SECTOR_GROUPS: Record<string, string[]> = {
    'Financial Sector': ['HDFC Bank', 'Bajaj Finance', 'ICICI Bank', 'Bajaj Housing', 'Savani Financials'],
    'Tech Sector': ['Affle India', 'LTI Mindtree', 'KPIT Tech', 'Tata Tech', 'BLS E-Services', 'Tanla', 'Infy', 'Happeist Mind'],
    'Consumer': ['Dmart', 'Tata Consumer', 'Pidilite'],
    'Power': ['Tata Power', 'KPI Green', 'Suzlon', 'Gensol'],
    'Pipe Sector': ['Hariom Pipes', 'Astral', 'Polycab'],
    'Others': ['Clean Science', 'Deepak Nitrite', 'Fine Organic', 'Gravita', 'SBI Life', 'Easemytrip']
};